// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rentCar.Models;

namespace rentCar.Migrations
{
    [DbContext(typeof(CarStuffContext))]
    [Migration("20210918152859_seventh")]
    partial class seventh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("rentCar.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChasisNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mark")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("rentCar.Models.CarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("carTypes");
                });

            modelBuilder.Entity("rentCar.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditCard")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("rentCar.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Able")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdmisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comision")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("rentCar.Models.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("fuelTypes");
                });

            modelBuilder.Entity("rentCar.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Car")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Client")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Employee")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FrontLeftWheel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FrontRightWheel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelQuantity")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GlassBroken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasScratches")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RearLeftWheel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RearRightWheel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReplacementRubber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.Property<string>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("inspections");
                });

            modelBuilder.Entity("rentCar.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("rentCar.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MarkId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("models");
                });

            modelBuilder.Entity("rentCar.Models.Rent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Car")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Client")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Employee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RentReturn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("able")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("rents");
                });
#pragma warning restore 612, 618
        }
    }
}
